### ISSUE TITLE
statusbarhidden

### ISSUE THREAD

**Issue by jteri3** [Awalz/Panel#1]
Hi,

How do you set status bar hidden for individual view controllers (or current view screen) instead of all view controllers?

Thanks

**Comment by Awalz** [comment]
Hey there,

the three View Controllers are Child ViewControllers of the container View Controller. You won't be able to directly control the appearance of the status bar from the Child View Controller

Instead, you should detect if the Container ViewController has moved to either the Left, Center, or Right Panel and adjust accordingly.

I have updated the Demo Project to include this functionality. I think it is a cool showcase of the Framework. Let me know if this helps.

Andrew

**Comment by jteri3** [comment]
Perfect. Thanks!
